/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import User.clientsForm;
import cateringsystem.loginForm;
import config.dbConnector;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class createClientForm extends javax.swing.JFrame {

    /**
     * Creates new form createUserForm
     */
    public createClientForm() {
        initComponents();
    }
    
    public String destination ="";
    File selectedFile;
    public String oldpath;
    public String path;
    
    Color hovercolor = new Color(255,4,4);
    Color navcolor = new Color(153,102,0);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        un = new javax.swing.JTextField();
        ut = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ps = new javax.swing.JPasswordField();
        cps = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        register = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        clientID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        usercancel = new javax.swing.JButton();
        userupdate = new javax.swing.JButton();
        userrefresh = new javax.swing.JButton();
        userclear = new javax.swing.JButton();
        userdelete = new javax.swing.JButton();
        pangan = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        apilido = new javax.swing.JTextField();
        klasiha = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        oras = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bayad = new javax.swing.JTextField();
        lugar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        contact1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        fn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("First Name:");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Last Name:");

        ln.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        em.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Email:");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Username:");

        un.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        ut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("User Type:");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Password:");

        cps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpsActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Confirm Pass:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Contact Num:");

        contact.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        cancel.setBackground(new java.awt.Color(153, 102, 0));
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        register.setBackground(new java.awt.Color(153, 102, 0));
        register.setText("Register");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerMouseExited(evt);
            }
        });
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 102, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CLIENT USER FORM");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 360, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 440, 50));

        clientID.setBackground(new java.awt.Color(153, 153, 0));
        clientID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        clientID.setEnabled(false);
        clientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientIDActionPerformed(evt);
            }
        });
        getContentPane().add(clientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 80, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("User ID:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 20));

        add.setBackground(new java.awt.Color(153, 102, 0));
        add.setText("ADD");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 90, -1));

        usercancel.setBackground(new java.awt.Color(153, 102, 0));
        usercancel.setText("CANCEL");
        usercancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usercancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usercancelMouseExited(evt);
            }
        });
        usercancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usercancelActionPerformed(evt);
            }
        });
        getContentPane().add(usercancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 90, -1));

        userupdate.setBackground(new java.awt.Color(153, 102, 0));
        userupdate.setText("UPDATE");
        userupdate.setEnabled(false);
        userupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userupdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userupdateMouseExited(evt);
            }
        });
        userupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userupdateActionPerformed(evt);
            }
        });
        getContentPane().add(userupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 90, -1));

        userrefresh.setBackground(new java.awt.Color(153, 102, 0));
        userrefresh.setText("REFRESH");
        userrefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userrefreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userrefreshMouseExited(evt);
            }
        });
        userrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userrefreshActionPerformed(evt);
            }
        });
        getContentPane().add(userrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 90, -1));

        userclear.setBackground(new java.awt.Color(153, 102, 0));
        userclear.setText("CLEAR");
        userclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userclearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userclearMouseExited(evt);
            }
        });
        userclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userclearActionPerformed(evt);
            }
        });
        getContentPane().add(userclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 90, -1));

        userdelete.setBackground(new java.awt.Color(153, 102, 0));
        userdelete.setText("DELETE");
        userdelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userdeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userdeleteMouseExited(evt);
            }
        });
        userdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(userdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 90, -1));

        pangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panganActionPerformed(evt);
            }
        });
        getContentPane().add(pangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, 30));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("LAST NAME");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 30));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FIRST NAME");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, 30));
        getContentPane().add(apilido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 150, 30));

        klasiha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "BIRTHDAY", "WEDDING", "REUNION", " " }));
        getContentPane().add(klasiha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 120, 30));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("TYPE OF EVENT");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 100, 30));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("DATE");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 100, 30));

        dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldActionPerformed(evt);
            }
        });
        getContentPane().add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 150, 30));
        getContentPane().add(oras, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 150, 30));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("TIME");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PAYMENT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 100, 30));
        getContentPane().add(bayad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 150, 30));

        lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugarActionPerformed(evt);
            }
        });
        getContentPane().add(lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 150, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PLACE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 100, 30));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("CONTACT");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 100, 30));

        contact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact1ActionPerformed(evt);
            }
        });
        getContentPane().add(contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 150, 30));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hala.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed

    }//GEN-LAST:event_emActionPerformed

    private void cpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpsActionPerformed

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
    
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited

    }//GEN-LAST:event_cancelMouseExited

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
      
    }//GEN-LAST:event_cancelActionPerformed

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseEntered
        add.setBackground(hovercolor);
    }//GEN-LAST:event_registerMouseEntered

    private void registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseExited
        add.setBackground(navcolor);
    }//GEN-LAST:event_registerMouseExited

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        
        if(pangan.getText().isEmpty()||apilido.getText().isEmpty()||dateField.getText().isEmpty()
            ||contact1.getText().isEmpty()||bayad.getText().isEmpty()||oras.getText().isEmpty() || lugar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"All fields are Required!");

        }else{
            dbConnector dbc = new dbConnector();

            if(dbc.insertData("INSERT INTO client_book(c_fname,c_lname,c_event,c_date,c_time,c_place,c_payment,c_contact)"
                + "VALUES('"+pangan.getText()+"','"+apilido.getText()+"','"+klasiha.getSelectedItem()+"','"+dateField.getText()+"','"+oras.getText()+"','"+lugar.getText()+"','"+bayad.getText()+"')"))
        {
            JOptionPane.showMessageDialog(null,"Inserted Successfully");
            usersForm uf = new usersForm();
            uf.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Connection Error!");
        }
        }

    }//GEN-LAST:event_registerActionPerformed

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(hovercolor);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(navcolor);
    }//GEN-LAST:event_addMouseExited

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

       if (pangan.getText().isEmpty() || apilido.getText().isEmpty()
        || lugar.getText().isEmpty() || dateField.getText().isEmpty()
        || oras.getText().isEmpty() || contact1.getText().isEmpty() || bayad.getText().isEmpty()) {

    JOptionPane.showMessageDialog(null, "All fields are required!");

} else if (!contact1.getText().matches("\\d{11}")) {
    JOptionPane.showMessageDialog(null, "Contact number must contain only digits and be 11 digits long.");
    contact1.setText("");

} else {
    dbConnector dbc = new dbConnector();

    String sql = "INSERT INTO client_book (c_fname, c_lname, c_event, c_date, c_time, c_place, c_payment, c_contact) "
               + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

    try {
        PreparedStatement pst = dbc.connect.prepareStatement(sql);
        pst.setString(1, pangan.getText());
        pst.setString(2, apilido.getText());
        pst.setString(3, klasiha.getSelectedItem().toString());
        pst.setString(4, dateField.getText());
        pst.setString(5, oras.getText());
        pst.setString(6, lugar.getText());
        pst.setString(7, bayad.getText());
        pst.setString(8, contact1.getText());

        int inserted = pst.executeUpdate();

        if (inserted > 0) {
            JOptionPane.showMessageDialog(null, "Booking added successfully!");
           clientsForm cf = new clientsForm();
           cf.setVisible(true);
           this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Insert failed.");
        }

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Database error: " + ex.getMessage());
    }
}

    

    }//GEN-LAST:event_addActionPerformed

    private void clientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientIDActionPerformed

    private void usercancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usercancelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_usercancelMouseEntered

    private void usercancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usercancelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_usercancelMouseExited

    private void usercancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usercancelActionPerformed
        clientsForm cf = new clientsForm();
        cf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_usercancelActionPerformed

    private void userupdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userupdateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_userupdateMouseEntered

    private void userupdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userupdateMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_userupdateMouseExited

    private void userupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userupdateActionPerformed
         if (pangan.getText().isEmpty() || apilido.getText().isEmpty()
    || lugar.getText().isEmpty() || dateField.getText().isEmpty()
    || oras.getText().isEmpty() || contact1.getText().isEmpty()) {

    JOptionPane.showMessageDialog(null, "Please fill in all fields.");

} else {
    dbConnector dbc = new dbConnector();

    try {
        String sql = "UPDATE client_book SET c_fname = ?, c_lname = ?, c_event = ?, c_date = ?, "
                   + "c_time = ?, c_place = ?, c_payment = ?, c_contact = ? WHERE c_id = ?";

        PreparedStatement pst = dbc.connect.prepareStatement(sql);
        pst.setString(1, pangan.getText());
        pst.setString(2, apilido.getText());
        pst.setString(3, klasiha.getSelectedItem().toString());
        pst.setString(4, dateField.getText());
        pst.setString(5, oras.getText());
        pst.setString(6, lugar.getText());
        pst.setString(7, bayad.getText());
        pst.setString(8, contact1.getText());
        pst.setString(9, clientID.getText());

        int updated = pst.executeUpdate();

        if (updated > 0) {
            JOptionPane.showMessageDialog(null, "Client updated successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Update failed. Record may not exist.");
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Connection Error: " + e.getMessage());
    }

    clientsForm cf = new clientsForm();
    cf.setVisible(true);
    this.dispose();
}

    }//GEN-LAST:event_userupdateActionPerformed

    private void userrefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userrefreshMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_userrefreshMouseEntered

    private void userrefreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userrefreshMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_userrefreshMouseExited

    private void userrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userrefreshActionPerformed
        
    }//GEN-LAST:event_userrefreshActionPerformed

    private void userclearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userclearMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_userclearMouseEntered

    private void userclearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userclearMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_userclearMouseExited

    private void userclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userclearActionPerformed
        
    }//GEN-LAST:event_userclearActionPerformed

    private void userdeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userdeleteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_userdeleteMouseEntered

    private void userdeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userdeleteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_userdeleteMouseExited

    private void userdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userdeleteActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this client?", 
                                            "Delete Confirmation", JOptionPane.YES_NO_OPTION);

if (confirm == JOptionPane.YES_OPTION) {
    dbConnector dbc = new dbConnector();

    try {
        String sql = "DELETE FROM client_book WHERE c_id = ?";
        PreparedStatement pst = dbc.connect.prepareStatement(sql);
        pst.setString(1, clientID.getText()); // Make sure clientID holds the correct ID

        int deleted = pst.executeUpdate();

        if (deleted > 0) {
            JOptionPane.showMessageDialog(null, "Client deleted successfully!");

            clientsForm cf = new clientsForm();
            cf.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Delete failed. Record may not exist.");
        }

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
}

    }//GEN-LAST:event_userdeleteActionPerformed

    private void lugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugarActionPerformed

    private void panganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panganActionPerformed

    private void contact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contact1ActionPerformed

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createClientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add;
    public javax.swing.JTextField apilido;
    public javax.swing.JTextField bayad;
    private javax.swing.JButton cancel;
    public javax.swing.JTextField clientID;
    private javax.swing.JTextField contact;
    public javax.swing.JTextField contact1;
    private javax.swing.JPasswordField cps;
    public javax.swing.JTextField dateField;
    private javax.swing.JTextField em;
    private javax.swing.JTextField fn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JComboBox<String> klasiha;
    private javax.swing.JTextField ln;
    public javax.swing.JTextField lugar;
    public javax.swing.JTextField oras;
    public javax.swing.JTextField pangan;
    private javax.swing.JPasswordField ps;
    private javax.swing.JButton register;
    private javax.swing.JTextField un;
    private javax.swing.JButton usercancel;
    private javax.swing.JButton userclear;
    private javax.swing.JButton userdelete;
    private javax.swing.JButton userrefresh;
    public javax.swing.JButton userupdate;
    private javax.swing.JComboBox<String> ut;
    // End of variables declaration//GEN-END:variables
}
